artifact_url = "https://github.com/BorrowSanitizer/rust/releases/download/"
tag = "rolling-1.92.0-dev-1fb6202"
sha = "1fb620206d680eb146cad5db6afc3450d2514818"
version = "1.92.0-dev"
dependencies = ["cmake", "ninja", "curl"]
targets = ["x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu"]
